# Generated by Django 3.0.6 on 2020-05-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail', '0002_auto_20200527_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='text',
            new_name='message',
        ),
    ]
